/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FantasyTeam = IDL.Record({
  'id' : IDL.Nat,
  'playerIds' : IDL.Vec(IDL.Nat),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'viceCaptainId' : IDL.Nat,
  'matchId' : IDL.Nat,
  'totalPoints' : IDL.Float64,
  'captainId' : IDL.Nat,
});
export const BallEvent = IDL.Record({
  'ball' : IDL.Text,
  'over' : IDL.Text,
  'runs' : IDL.Nat,
  'batter' : IDL.Text,
  'description' : IDL.Text,
  'bowler' : IDL.Text,
  'isWicket' : IDL.Bool,
  'timestamp' : IDL.Int,
  'isSix' : IDL.Bool,
  'isBoundary' : IDL.Bool,
});
export const ContestType = IDL.Variant({
  'Practice' : IDL.Null,
  'Head2Head' : IDL.Null,
  'MegaLeague' : IDL.Null,
  'MiniLeague' : IDL.Null,
});
export const Contest = IDL.Record({
  'id' : IDL.Nat,
  'contestType' : ContestType,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'prizeBreakdown' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'matchId' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'filledSpots' : IDL.Nat,
  'maxEntries' : IDL.Nat,
  'prizePool' : IDL.Nat,
});
export const ContestEntry = IDL.Record({
  'contestId' : IDL.Nat,
  'owner' : IDL.Principal,
  'joinedAt' : IDL.Int,
  'rank' : IDL.Opt(IDL.Nat),
  'prize' : IDL.Nat,
  'teamId' : IDL.Nat,
  'points' : IDL.Float64,
});
export const LeaderboardEntry = IDL.Record({
  'teamName' : IDL.Text,
  'principal' : IDL.Principal,
  'rank' : IDL.Nat,
  'prize' : IDL.Nat,
  'points' : IDL.Float64,
});
export const MatchStatus = IDL.Variant({
  'Live' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Upcoming' : IDL.Null,
});
export const Team = IDL.Record({
  'code' : IDL.Text,
  'logo' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const Sport = IDL.Variant({
  'Football' : IDL.Null,
  'Cricket' : IDL.Null,
  'Kabaddi' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'status' : MatchStatus,
  'teamA' : Team,
  'teamB' : Team,
  'venue' : IDL.Text,
  'scoreA' : IDL.Opt(IDL.Text),
  'scoreB' : IDL.Opt(IDL.Text),
  'lastUpdated' : IDL.Int,
  'sport' : Sport,
  'ballHistory' : IDL.Vec(BallEvent),
  'currentOver' : IDL.Opt(IDL.Text),
  'liveStatus' : IDL.Opt(IDL.Text),
});
export const PlayerRole = IDL.Variant({
  'Defender2' : IDL.Null,
  'Goalkeeper' : IDL.Null,
  'AllRounder' : IDL.Null,
  'WicketKeeper' : IDL.Null,
  'Batsman' : IDL.Null,
  'Bowler' : IDL.Null,
  'AllRounderKabaddi' : IDL.Null,
  'Midfielder' : IDL.Null,
  'Forward' : IDL.Null,
  'Defender' : IDL.Null,
  'Raider' : IDL.Null,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'country' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : PlayerRole,
  'team' : IDL.Text,
  'selPct' : IDL.Float64,
  'credit' : IDL.Float64,
  'matchId' : IDL.Nat,
  'points' : IDL.Float64,
  'avatar' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TransactionKind = IDL.Variant({
  'Deposit' : IDL.Null,
  'Refund' : IDL.Null,
  'Withdrawal' : IDL.Null,
  'PrizeCredit' : IDL.Null,
  'ContestEntry' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'kind' : TransactionKind,
  'note' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'joinedAt' : IDL.Int,
  'phone' : IDL.Opt(IDL.Text),
  'kycDone' : IDL.Bool,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addSampleContest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'confirmPayment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createCheckoutSession' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'createTeam' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Nat, IDL.Nat],
      [FantasyTeam],
      [],
    ),
  'getApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getBallHistory' : IDL.Func([IDL.Nat], [IDL.Vec(BallEvent)], ['query']),
  'getContest' : IDL.Func([IDL.Nat], [IDL.Opt(Contest)], ['query']),
  'getContestHistory' : IDL.Func([], [IDL.Vec(ContestEntry)], ['query']),
  'getContests' : IDL.Func([IDL.Nat], [IDL.Vec(Contest)], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getMyTeams' : IDL.Func([], [IDL.Vec(FantasyTeam)], ['query']),
  'getPlayers' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'joinContest' : IDL.Func([IDL.Nat, IDL.Nat], [ContestEntry], []),
  'refreshLiveScores' : IDL.Func([], [], []),
  'setApiKey' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUserProfile' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [UserProfile], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'withdrawRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FantasyTeam = IDL.Record({
    'id' : IDL.Nat,
    'playerIds' : IDL.Vec(IDL.Nat),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'viceCaptainId' : IDL.Nat,
    'matchId' : IDL.Nat,
    'totalPoints' : IDL.Float64,
    'captainId' : IDL.Nat,
  });
  const BallEvent = IDL.Record({
    'ball' : IDL.Text,
    'over' : IDL.Text,
    'runs' : IDL.Nat,
    'batter' : IDL.Text,
    'description' : IDL.Text,
    'bowler' : IDL.Text,
    'isWicket' : IDL.Bool,
    'timestamp' : IDL.Int,
    'isSix' : IDL.Bool,
    'isBoundary' : IDL.Bool,
  });
  const ContestType = IDL.Variant({
    'Practice' : IDL.Null,
    'Head2Head' : IDL.Null,
    'MegaLeague' : IDL.Null,
    'MiniLeague' : IDL.Null,
  });
  const Contest = IDL.Record({
    'id' : IDL.Nat,
    'contestType' : ContestType,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'prizeBreakdown' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'matchId' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'filledSpots' : IDL.Nat,
    'maxEntries' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  const ContestEntry = IDL.Record({
    'contestId' : IDL.Nat,
    'owner' : IDL.Principal,
    'joinedAt' : IDL.Int,
    'rank' : IDL.Opt(IDL.Nat),
    'prize' : IDL.Nat,
    'teamId' : IDL.Nat,
    'points' : IDL.Float64,
  });
  const LeaderboardEntry = IDL.Record({
    'teamName' : IDL.Text,
    'principal' : IDL.Principal,
    'rank' : IDL.Nat,
    'prize' : IDL.Nat,
    'points' : IDL.Float64,
  });
  const MatchStatus = IDL.Variant({
    'Live' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Upcoming' : IDL.Null,
  });
  const Team = IDL.Record({
    'code' : IDL.Text,
    'logo' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const Sport = IDL.Variant({
    'Football' : IDL.Null,
    'Cricket' : IDL.Null,
    'Kabaddi' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'status' : MatchStatus,
    'teamA' : Team,
    'teamB' : Team,
    'venue' : IDL.Text,
    'scoreA' : IDL.Opt(IDL.Text),
    'scoreB' : IDL.Opt(IDL.Text),
    'lastUpdated' : IDL.Int,
    'sport' : Sport,
    'ballHistory' : IDL.Vec(BallEvent),
    'currentOver' : IDL.Opt(IDL.Text),
    'liveStatus' : IDL.Opt(IDL.Text),
  });
  const PlayerRole = IDL.Variant({
    'Defender2' : IDL.Null,
    'Goalkeeper' : IDL.Null,
    'AllRounder' : IDL.Null,
    'WicketKeeper' : IDL.Null,
    'Batsman' : IDL.Null,
    'Bowler' : IDL.Null,
    'AllRounderKabaddi' : IDL.Null,
    'Midfielder' : IDL.Null,
    'Forward' : IDL.Null,
    'Defender' : IDL.Null,
    'Raider' : IDL.Null,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'country' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : PlayerRole,
    'team' : IDL.Text,
    'selPct' : IDL.Float64,
    'credit' : IDL.Float64,
    'matchId' : IDL.Nat,
    'points' : IDL.Float64,
    'avatar' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TransactionKind = IDL.Variant({
    'Deposit' : IDL.Null,
    'Refund' : IDL.Null,
    'Withdrawal' : IDL.Null,
    'PrizeCredit' : IDL.Null,
    'ContestEntry' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'kind' : TransactionKind,
    'note' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'joinedAt' : IDL.Int,
    'phone' : IDL.Opt(IDL.Text),
    'kycDone' : IDL.Bool,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addSampleContest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'confirmPayment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createCheckoutSession' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'createTeam' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Nat, IDL.Nat],
        [FantasyTeam],
        [],
      ),
    'getApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getBallHistory' : IDL.Func([IDL.Nat], [IDL.Vec(BallEvent)], ['query']),
    'getContest' : IDL.Func([IDL.Nat], [IDL.Opt(Contest)], ['query']),
    'getContestHistory' : IDL.Func([], [IDL.Vec(ContestEntry)], ['query']),
    'getContests' : IDL.Func([IDL.Nat], [IDL.Vec(Contest)], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getMyTeams' : IDL.Func([], [IDL.Vec(FantasyTeam)], ['query']),
    'getPlayers' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'joinContest' : IDL.Func([IDL.Nat, IDL.Nat], [ContestEntry], []),
    'refreshLiveScores' : IDL.Func([], [], []),
    'setApiKey' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUserProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [UserProfile],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'withdrawRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };