/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contest {
  'id' : bigint,
  'contestType' : ContestType,
  'name' : string,
  'createdAt' : bigint,
  'prizeBreakdown' : Array<[bigint, bigint]>,
  'matchId' : bigint,
  'entryFee' : bigint,
  'filledSpots' : bigint,
  'maxEntries' : bigint,
  'prizePool' : bigint,
}
export interface ContestEntry {
  'contestId' : bigint,
  'owner' : Principal,
  'joinedAt' : bigint,
  'rank' : [] | [bigint],
  'prize' : bigint,
  'teamId' : bigint,
  'points' : number,
}
export type ContestType = { 'Practice' : null } |
  { 'Head2Head' : null } |
  { 'MegaLeague' : null } |
  { 'MiniLeague' : null };
export interface FantasyTeam {
  'id' : bigint,
  'playerIds' : Array<bigint>,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'viceCaptainId' : bigint,
  'matchId' : bigint,
  'totalPoints' : number,
  'captainId' : bigint,
}
export interface LeaderboardEntry {
  'teamName' : string,
  'principal' : Principal,
  'rank' : bigint,
  'prize' : bigint,
  'points' : number,
}
export interface Match {
  'id' : bigint,
  'startTime' : bigint,
  'status' : MatchStatus,
  'teamA' : Team,
  'teamB' : Team,
  'venue' : string,
  'scoreA' : [] | [string],
  'scoreB' : [] | [string],
  'lastUpdated' : bigint,
  'sport' : Sport,
}
export type MatchStatus = { 'Live' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Upcoming' : null };
export interface Player {
  'id' : bigint,
  'name' : string,
  'role' : PlayerRole,
  'team' : string,
  'selPct' : number,
  'credit' : number,
  'matchId' : bigint,
  'points' : number,
}
export type PlayerRole = { 'Defender2' : null } |
  { 'Goalkeeper' : null } |
  { 'AllRounder' : null } |
  { 'WicketKeeper' : null } |
  { 'Batsman' : null } |
  { 'Bowler' : null } |
  { 'AllRounderKabaddi' : null } |
  { 'Midfielder' : null } |
  { 'Forward' : null } |
  { 'Defender' : null } |
  { 'Raider' : null };
export type Sport = { 'Football' : null } |
  { 'Cricket' : null } |
  { 'Kabaddi' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Team {
  'code' : string,
  'logo' : [] | [string],
  'name' : string,
}
export interface Transaction {
  'id' : bigint,
  'owner' : Principal,
  'kind' : TransactionKind,
  'note' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type TransactionKind = { 'Deposit' : null } |
  { 'Refund' : null } |
  { 'Withdrawal' : null } |
  { 'PrizeCredit' : null } |
  { 'ContestEntry' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'joinedAt' : bigint,
  'phone' : [] | [string],
  'kycDone' : boolean,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addSampleContest' : ActorMethod<[string, bigint, bigint, string], boolean>,
  'confirmPayment' : ActorMethod<[string], boolean>,
  'createCheckoutSession' : ActorMethod<[bigint], string>,
  'createTeam' : ActorMethod<
    [bigint, string, Array<bigint>, bigint, bigint],
    FantasyTeam
  >,
  'getContest' : ActorMethod<[bigint], [] | [Contest]>,
  'getContestHistory' : ActorMethod<[], Array<ContestEntry>>,
  'getContests' : ActorMethod<[bigint], Array<Contest>>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getMatch' : ActorMethod<[bigint], [] | [Match]>,
  'getMatches' : ActorMethod<[], Array<Match>>,
  'getMyTeams' : ActorMethod<[], Array<FantasyTeam>>,
  'getPlayers' : ActorMethod<[bigint], Array<Player>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'joinContest' : ActorMethod<[bigint, bigint], ContestEntry>,
  'refreshLiveScores' : ActorMethod<[], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUserProfile' : ActorMethod<[string, [] | [string]], UserProfile>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'withdrawRequest' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];