/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    name: string;
    role: PlayerRole;
    team: string;
    selPct: number;
    credit: number;
    matchId: bigint;
    points: number;
}
export interface LeaderboardEntry {
    teamName: string;
    principal: Principal;
    rank: bigint;
    prize: bigint;
    points: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FantasyTeam {
    id: bigint;
    playerIds: Array<bigint>;
    owner: Principal;
    name: string;
    createdAt: bigint;
    viceCaptainId: bigint;
    matchId: bigint;
    totalPoints: number;
    captainId: bigint;
}
export interface Match {
    id: bigint;
    startTime: bigint;
    status: MatchStatus;
    teamA: Team;
    teamB: Team;
    venue: string;
    scoreA?: string;
    scoreB?: string;
    lastUpdated: bigint;
    sport: Sport;
}
export interface http_header {
    value: string;
    name: string;
}
export interface Transaction {
    id: bigint;
    owner: Principal;
    kind: TransactionKind;
    note: string;
    timestamp: bigint;
    amount: bigint;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Contest {
    id: bigint;
    contestType: ContestType;
    name: string;
    createdAt: bigint;
    prizeBreakdown: Array<[bigint, bigint]>;
    matchId: bigint;
    entryFee: bigint;
    filledSpots: bigint;
    maxEntries: bigint;
    prizePool: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ContestEntry {
    contestId: bigint;
    owner: Principal;
    joinedAt: bigint;
    rank?: bigint;
    prize: bigint;
    teamId: bigint;
    points: number;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    principal: Principal;
    username: string;
    joinedAt: bigint;
    phone?: string;
    kycDone: boolean;
}
export interface Team {
    code: string;
    logo?: string;
    name: string;
}
export enum ContestType {
    Practice = "Practice",
    Head2Head = "Head2Head",
    MegaLeague = "MegaLeague",
    MiniLeague = "MiniLeague"
}
export enum MatchStatus {
    Live = "Live",
    Cancelled = "Cancelled",
    Completed = "Completed",
    Upcoming = "Upcoming"
}
export enum PlayerRole {
    Defender2 = "Defender2",
    Goalkeeper = "Goalkeeper",
    AllRounder = "AllRounder",
    WicketKeeper = "WicketKeeper",
    Batsman = "Batsman",
    Bowler = "Bowler",
    AllRounderKabaddi = "AllRounderKabaddi",
    Midfielder = "Midfielder",
    Forward = "Forward",
    Defender = "Defender",
    Raider = "Raider"
}
export enum Sport {
    Football = "Football",
    Cricket = "Cricket",
    Kabaddi = "Kabaddi"
}
export enum TransactionKind {
    Deposit = "Deposit",
    Refund = "Refund",
    Withdrawal = "Withdrawal",
    PrizeCredit = "PrizeCredit",
    ContestEntry = "ContestEntry"
}
export interface backendInterface {
    addSampleContest(matchId: string, entryFee: bigint, prizePool: bigint, name: string): Promise<boolean>;
    confirmPayment(sessionId: string): Promise<boolean>;
    createCheckoutSession(amount: bigint): Promise<string>;
    createTeam(matchId: bigint, name: string, playerIds: Array<bigint>, captainId: bigint, viceCaptainId: bigint): Promise<FantasyTeam>;
    getContest(contestId: bigint): Promise<Contest | null>;
    getContestHistory(): Promise<Array<ContestEntry>>;
    getContests(matchId: bigint): Promise<Array<Contest>>;
    getLeaderboard(contestId: bigint): Promise<Array<LeaderboardEntry>>;
    getMatch(matchId: bigint): Promise<Match | null>;
    getMatches(): Promise<Array<Match>>;
    getMyTeams(): Promise<Array<FantasyTeam>>;
    getPlayers(matchId: bigint): Promise<Array<Player>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserProfile(): Promise<UserProfile | null>;
    getWalletBalance(): Promise<bigint>;
    isStripeConfigured(): Promise<boolean>;
    joinContest(contestId: bigint, teamId: bigint): Promise<ContestEntry>;
    refreshLiveScores(): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setUserProfile(username: string, phone: string | null): Promise<UserProfile>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    withdrawRequest(amount: bigint): Promise<boolean>;
}
import type { Contest as _Contest, ContestEntry as _ContestEntry, ContestType as _ContestType, Match as _Match, MatchStatus as _MatchStatus, Player as _Player, PlayerRole as _PlayerRole, Sport as _Sport, StripeSessionStatus as _StripeSessionStatus, Team as _Team, Transaction as _Transaction, TransactionKind as _TransactionKind, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSampleContest(arg0: string, arg1: bigint, arg2: bigint, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addSampleContest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSampleContest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async confirmPayment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0);
            return result;
        }
    }
    async createTeam(arg0: bigint, arg1: string, arg2: Array<bigint>, arg3: bigint, arg4: bigint): Promise<FantasyTeam> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeam(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeam(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getContest(arg0: bigint): Promise<Contest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContest(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContest(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContestHistory(): Promise<Array<ContestEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContestHistory();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContestHistory();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContests(arg0: bigint): Promise<Array<Contest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContests(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContests(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return result;
        }
    }
    async getMatch(arg0: bigint): Promise<Match | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTeams(): Promise<Array<FantasyTeam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTeams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTeams();
            return result;
        }
    }
    async getPlayers(arg0: bigint): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayers(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayers(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async joinContest(arg0: bigint, arg1: bigint): Promise<ContestEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.joinContest(arg0, arg1);
                return from_candid_ContestEntry_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinContest(arg0, arg1);
            return from_candid_ContestEntry_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async refreshLiveScores(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshLiveScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshLiveScores();
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setUserProfile(arg0: string, arg1: string | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfile(arg0, to_candid_opt_n38(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfile_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfile(arg0, to_candid_opt_n38(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfile_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async withdrawRequest(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawRequest(arg0);
            return result;
        }
    }
}
function from_candid_ContestEntry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContestEntry): ContestEntry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ContestType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContestType): ContestType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Contest_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contest): Contest {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerRole): PlayerRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Sport_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sport): Sport {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionKind_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionKind): TransactionKind {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contest]): Contest | null {
    return value.length === 0 ? null : from_candid_Contest_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Match]): Match | null {
    return value.length === 0 ? null : from_candid_Match_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: bigint;
    status: _MatchStatus;
    teamA: _Team;
    teamB: _Team;
    venue: string;
    scoreA: [] | [string];
    scoreB: [] | [string];
    lastUpdated: bigint;
    sport: _Sport;
}): {
    id: bigint;
    startTime: bigint;
    status: MatchStatus;
    teamA: Team;
    teamB: Team;
    venue: string;
    scoreA?: string;
    scoreB?: string;
    lastUpdated: bigint;
    sport: Sport;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_MatchStatus_n14(_uploadFile, _downloadFile, value.status),
        teamA: from_candid_Team_n16(_uploadFile, _downloadFile, value.teamA),
        teamB: from_candid_Team_n16(_uploadFile, _downloadFile, value.teamB),
        venue: value.venue,
        scoreA: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.scoreA)),
        scoreB: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.scoreB)),
        lastUpdated: value.lastUpdated,
        sport: from_candid_Sport_n19(_uploadFile, _downloadFile, value.sport)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    code: string;
    logo: [] | [string];
    name: string;
}): {
    code: string;
    logo?: string;
    name: string;
} {
    return {
        code: value.code,
        logo: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.logo)),
        name: value.name
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: _PlayerRole;
    team: string;
    selPct: number;
    credit: number;
    matchId: bigint;
    points: number;
}): {
    id: bigint;
    name: string;
    role: PlayerRole;
    team: string;
    selPct: number;
    credit: number;
    matchId: bigint;
    points: number;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_PlayerRole_n25(_uploadFile, _downloadFile, value.role),
        team: value.team,
        selPct: value.selPct,
        credit: value.credit,
        matchId: value.matchId,
        points: value.points
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    contestType: _ContestType;
    name: string;
    createdAt: bigint;
    prizeBreakdown: Array<[bigint, bigint]>;
    matchId: bigint;
    entryFee: bigint;
    filledSpots: bigint;
    maxEntries: bigint;
    prizePool: bigint;
}): {
    id: bigint;
    contestType: ContestType;
    name: string;
    createdAt: bigint;
    prizeBreakdown: Array<[bigint, bigint]>;
    matchId: bigint;
    entryFee: bigint;
    filledSpots: bigint;
    maxEntries: bigint;
    prizePool: bigint;
} {
    return {
        id: value.id,
        contestType: from_candid_ContestType_n4(_uploadFile, _downloadFile, value.contestType),
        name: value.name,
        createdAt: value.createdAt,
        prizeBreakdown: value.prizeBreakdown,
        matchId: value.matchId,
        entryFee: value.entryFee,
        filledSpots: value.filledSpots,
        maxEntries: value.maxEntries,
        prizePool: value.prizePool
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: Principal;
    kind: _TransactionKind;
    note: string;
    timestamp: bigint;
    amount: bigint;
}): {
    id: bigint;
    owner: Principal;
    kind: TransactionKind;
    note: string;
    timestamp: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        owner: value.owner,
        kind: from_candid_TransactionKind_n33(_uploadFile, _downloadFile, value.kind),
        note: value.note,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    username: string;
    joinedAt: bigint;
    phone: [] | [string];
    kycDone: boolean;
}): {
    principal: Principal;
    username: string;
    joinedAt: bigint;
    phone?: string;
    kycDone: boolean;
} {
    return {
        principal: value.principal,
        username: value.username,
        joinedAt: value.joinedAt,
        phone: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.phone)),
        kycDone: value.kycDone
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contestId: bigint;
    owner: Principal;
    joinedAt: bigint;
    rank: [] | [bigint];
    prize: bigint;
    teamId: bigint;
    points: number;
}): {
    contestId: bigint;
    owner: Principal;
    joinedAt: bigint;
    rank?: bigint;
    prize: bigint;
    teamId: bigint;
    points: number;
} {
    return {
        contestId: value.contestId,
        owner: value.owner,
        joinedAt: value.joinedAt,
        rank: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.rank)),
        prize: value.prize,
        teamId: value.teamId,
        points: value.points
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Live: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Upcoming: null;
}): MatchStatus {
    return "Live" in value ? MatchStatus.Live : "Cancelled" in value ? MatchStatus.Cancelled : "Completed" in value ? MatchStatus.Completed : "Upcoming" in value ? MatchStatus.Upcoming : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Football: null;
} | {
    Cricket: null;
} | {
    Kabaddi: null;
}): Sport {
    return "Football" in value ? Sport.Football : "Cricket" in value ? Sport.Cricket : "Kabaddi" in value ? Sport.Kabaddi : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Defender2: null;
} | {
    Goalkeeper: null;
} | {
    AllRounder: null;
} | {
    WicketKeeper: null;
} | {
    Batsman: null;
} | {
    Bowler: null;
} | {
    AllRounderKabaddi: null;
} | {
    Midfielder: null;
} | {
    Forward: null;
} | {
    Defender: null;
} | {
    Raider: null;
}): PlayerRole {
    return "Defender2" in value ? PlayerRole.Defender2 : "Goalkeeper" in value ? PlayerRole.Goalkeeper : "AllRounder" in value ? PlayerRole.AllRounder : "WicketKeeper" in value ? PlayerRole.WicketKeeper : "Batsman" in value ? PlayerRole.Batsman : "Bowler" in value ? PlayerRole.Bowler : "AllRounderKabaddi" in value ? PlayerRole.AllRounderKabaddi : "Midfielder" in value ? PlayerRole.Midfielder : "Forward" in value ? PlayerRole.Forward : "Defender" in value ? PlayerRole.Defender : "Raider" in value ? PlayerRole.Raider : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n29(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Deposit: null;
} | {
    Refund: null;
} | {
    Withdrawal: null;
} | {
    PrizeCredit: null;
} | {
    ContestEntry: null;
}): TransactionKind {
    return "Deposit" in value ? TransactionKind.Deposit : "Refund" in value ? TransactionKind.Refund : "Withdrawal" in value ? TransactionKind.Withdrawal : "PrizeCredit" in value ? TransactionKind.PrizeCredit : "ContestEntry" in value ? TransactionKind.ContestEntry : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Practice: null;
} | {
    Head2Head: null;
} | {
    MegaLeague: null;
} | {
    MiniLeague: null;
}): ContestType {
    return "Practice" in value ? ContestType.Practice : "Head2Head" in value ? ContestType.Head2Head : "MegaLeague" in value ? ContestType.MegaLeague : "MiniLeague" in value ? ContestType.MiniLeague : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contest>): Array<Contest> {
    return value.map((x)=>from_candid_Contest_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContestEntry>): Array<ContestEntry> {
    return value.map((x)=>from_candid_ContestEntry_n7(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
